$ErrorActionPreference = 'Stop'

param(
    [switch]$SkipProfileUpdate
)

function Escape-SingleQuote {
    param([string]$Value)
    if ($null -eq $Value) { return '' }
    return $Value -replace "'", "''"
}

function Get-EnvValue {
    param(
        [string]$Prompt,
        [string]$CurrentValue,
        [switch]$Secret
    )

    if (-not [string]::IsNullOrWhiteSpace($CurrentValue) -and $CurrentValue -notlike 'replace-with-your-own-*') {
        return $CurrentValue
    }

    if ($Secret) {
        $secure = Read-Host -Prompt $Prompt -AsSecureString
        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
        try {
            return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
        }
        finally {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        }
    }

    return Read-Host -Prompt $Prompt
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$skillDir = Split-Path -Parent $scriptDir
$template = Join-Path $skillDir 'assets\env.template.ps1'
$localEnv = Join-Path $skillDir 'local.env.ps1'

if (-not (Test-Path $template)) {
    throw "Template not found: $template"
}

if (-not (Test-Path $localEnv)) {
    Copy-Item $template $localEnv -Force
    Write-Host "Created local env template: $localEnv"
}

# 先加载已有值，避免每次都输入。
. $localEnv

$token = Get-EnvValue -Prompt '请输入 TAPD_API_TOKEN' -CurrentValue $env:TAPD_API_TOKEN -Secret
$user = Get-EnvValue -Prompt '请输入 TAPD_API_USER' -CurrentValue $env:TAPD_API_USER
$password = Get-EnvValue -Prompt '请输入 TAPD_API_PASSWORD' -CurrentValue $env:TAPD_API_PASSWORD -Secret
$baseUrl = Get-EnvValue -Prompt '请输入 TAPD_API_BASE_URL（回车使用默认 https://api.tapd.cn）' -CurrentValue $env:TAPD_API_BASE_URL
$companyId = Get-EnvValue -Prompt '请输入 TAPD_COMPANY_ID（回车使用默认 66514098）' -CurrentValue $env:TAPD_COMPANY_ID
$webBaseUrl = Get-EnvValue -Prompt '请输入 TAPD_WEB_BASE_URL（回车使用默认 https://www.tapd.cn）' -CurrentValue $env:TAPD_WEB_BASE_URL
$webStorageState = Get-EnvValue -Prompt '请输入 TAPD_WEB_STORAGE_STATE（可留空，例如 .github/skills/tapd-bug-regression/tapd.storage-state.json）' -CurrentValue $env:TAPD_WEB_STORAGE_STATE

if ([string]::IsNullOrWhiteSpace($baseUrl)) {
    $baseUrl = 'https://api.tapd.cn'
}
if ([string]::IsNullOrWhiteSpace($companyId)) {
    $companyId = '66514098'
}
if ([string]::IsNullOrWhiteSpace($webBaseUrl)) {
    $webBaseUrl = 'https://www.tapd.cn'
}

$localEnvContent = @(
    '# Auto-generated by bootstrap-user-env.ps1',
    '# Never commit this file.',
    "$env:TAPD_API_TOKEN = '$(Escape-SingleQuote $token)'",
    "$env:TAPD_API_USER = '$(Escape-SingleQuote $user)'",
    "$env:TAPD_API_PASSWORD = '$(Escape-SingleQuote $password)'",
    "$env:TAPD_API_BASE_URL = '$(Escape-SingleQuote $baseUrl)'",
    "$env:TAPD_COMPANY_ID = '$(Escape-SingleQuote $companyId)'",
    "$env:TAPD_WEB_BASE_URL = '$(Escape-SingleQuote $webBaseUrl)'",
    "$env:TAPD_WEB_STORAGE_STATE = '$(Escape-SingleQuote $webStorageState)'"
)

Set-Content -Path $localEnv -Value $localEnvContent -Encoding UTF8

# 写入当前会话环境变量
$env:TAPD_API_TOKEN = $token
$env:TAPD_API_USER = $user
$env:TAPD_API_PASSWORD = $password
$env:TAPD_API_BASE_URL = $baseUrl
$env:TAPD_COMPANY_ID = $companyId
$env:TAPD_WEB_BASE_URL = $webBaseUrl
$env:TAPD_WEB_STORAGE_STATE = $webStorageState

if (-not $SkipProfileUpdate) {
    if (-not (Test-Path $PROFILE)) {
        New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    }

    $profileLine = ". '$localEnv'"
    $profileContent = Get-Content -Path $PROFILE -Raw
    if ($profileContent -notmatch [regex]::Escape($profileLine)) {
        Add-Content -Path $PROFILE -Value "`r`n$profileLine"
        Write-Host "Added auto-load to profile: $PROFILE"
    }
}

Write-Host 'TAPD local env is ready.'
Write-Host "local.env.ps1: $localEnv"
Write-Host 'Current shell already loaded these env vars.'
if ($SkipProfileUpdate) {
    Write-Host "Tip: run '. $localEnv' in every new shell."
}
